print("Sandor är bäst")
print('rumpa')
print('banan')
print('vigor är en bajs korv')
print('elvina är best')
print('groda')
print('löv')
print('\n')
print(100000*230000000)
print('jag älskar fisk')
print('groda är gott')
print('takos är gott och smarit')
print('kamelen är so stor')
print('gås')
print('jag har en bra mamma')
print('jag har en bra borsa')
print('faster är så snel')
print('pumpor kan vara lite leskiga i bland')
print('is är halkit')
print('nårsken är fint')
print('julen är best')
print('')
print('fanta är gått')
print('skolan är rolig')
print('vaten är gott')
print('varjar är farliga')
print(18888990*45-98)
